ruby '2.1.5'
source 'https://rubygems.org'

gem 'pooler', git: 'https://github.com/amancevice/pooler.git' #path: "#{ENV['HOME']}/smallweirdnumber/pooler"
gem 'rake'
gem 'sass'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-assetpack', require: 'sinatra/assetpack'
gem 'sinatra-contrib',   require: 'sinatra/cookies'
gem 'sinatra-flash',     require: 'sinatra/flash'
gem 'thin'

group :development do
  gem 'pry'
  gem 'sqlite3'
end

group :production do
  gem 'pg'
end
