require './oscars'
require 'sinatra/activerecord/rake'

# Rakefile
APP_FILE  = 'oscars.rb'
APP_CLASS = 'Oscars'

# For Padrino users, do not forget to add your application namspace
# APP_CLASS = '<Project>::App'

require 'sinatra/assetpack/rake'